<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260411095242 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE agence (id UUID NOT NULL, nom_agc VARCHAR(255) NOT NULL, creation_agc DATE DEFAULT NULL, nomen_agc VARCHAR(180) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19AA9FA9995D4 ON agence (nom_agc)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19AA9CB45F50E ON agence (nomen_agc)');
        $this->addSql('CREATE TABLE agence_personnel (id UUID NOT NULL, agence_id_id UUID DEFAULT NULL, personnel_id_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_28239427D1F6E7C3 ON agence_personnel (agence_id_id)');
        $this->addSql('CREATE INDEX IDX_28239427588DF5E9 ON agence_personnel (personnel_id_id)');
        $this->addSql('CREATE TABLE categorie (id UUID NOT NULL, designation VARCHAR(10) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_497DD6348947610D ON categorie (designation)');
        $this->addSql('CREATE TABLE conjoint (id UUID NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, date_naiss DATE DEFAULT NULL, profession VARCHAR(255) DEFAULT NULL, personnel_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2F91A10D1C109075 ON conjoint (personnel_id)');
        $this->addSql('CREATE TABLE direction (id UUID NOT NULL, nom_dir VARCHAR(255) NOT NULL, nomen_dir VARCHAR(180) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E4AD1B38615A43 ON direction (nom_dir)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E4AD1B339BD3A99 ON direction (nomen_dir)');
        $this->addSql('CREATE TABLE direction_personnel (id UUID NOT NULL, personnel_id_id UUID DEFAULT NULL, service_id_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD9C37A9588DF5E9 ON direction_personnel (personnel_id_id)');
        $this->addSql('CREATE INDEX IDX_CD9C37A9D63673B0 ON direction_personnel (service_id_id)');
        $this->addSql('CREATE TABLE document (id UUID NOT NULL, reference VARCHAR(255) NOT NULL, fichier VARCHAR(255) NOT NULL, titre VARCHAR(255) DEFAULT NULL, titulaire VARCHAR(255) DEFAULT NULL, date_arrive_doc DATE DEFAULT NULL, description TEXT DEFAULT NULL, creation_doc TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, maj_doc TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statuc_doc VARCHAR(255) DEFAULT \'Brouillon\' NOT NULL, personnel_id_id UUID NOT NULL, type_document_id_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D8698A76AEA34913 ON document (reference)');
        $this->addSql('CREATE INDEX IDX_D8698A76588DF5E9 ON document (personnel_id_id)');
        $this->addSql('CREATE INDEX IDX_D8698A764026C1B1 ON document (type_document_id_id)');
        $this->addSql('CREATE TABLE dossier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_dos VARCHAR(255) NOT NULL, nomenclature VARCHAR(255) NOT NULL, niveau_conf VARCHAR(255) DEFAULT \'Public\' NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D48E037293CCD53 ON dossier (nom_dos)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3D48E037799A3652 ON dossier (nomenclature)');
        $this->addSql('CREATE TABLE enfant (id UUID NOT NULL, nom VARCHAR(255) NOT NULL, prenom VARCHAR(255) NOT NULL, date_naiss DATE DEFAULT NULL, sexe VARCHAR(255) NOT NULL, personnel_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_34B70CA21C109075 ON enfant (personnel_id)');
        $this->addSql('CREATE TABLE fonction (id UUID NOT NULL, nom_fon VARCHAR(255) NOT NULL, categorie_id_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_900D5BD49BE75E4 ON fonction (nom_fon)');
        $this->addSql('CREATE INDEX IDX_900D5BD8A3C7387 ON fonction (categorie_id_id)');
        $this->addSql('CREATE TABLE personnel (id UUID NOT NULL, username VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, im INT NOT NULL, nom_ag VARCHAR(255) NOT NULL, prenom_ag VARCHAR(255) NOT NULL, date_naiss_ag DATE NOT NULL, date_entre DATE NOT NULL, adresse_ag VARCHAR(255) DEFAULT NULL, mail_ag VARCHAR(255) DEFAULT NULL, contact_ag JSON DEFAULT NULL, creation_compte TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, maj_compte TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dernier_connexion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status_compte VARCHAR(255) DEFAULT \'Inactif\' NOT NULL, sexe VARCHAR(255) NOT NULL, situation_familial VARCHAR(255) DEFAULT \'Célibataire\' NOT NULL, photo_profil VARCHAR(255) DEFAULT NULL, back_front BOOLEAN NOT NULL, fonction_id_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A6BCF3DE35C246D5 ON personnel (password)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A6BCF3DEC6E5DFF4 ON personnel (im)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A6BCF3DE99A7B4B3 ON personnel (mail_ag)');
        $this->addSql('CREATE INDEX IDX_A6BCF3DE1DECB9C6 ON personnel (fonction_id_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_USERNAME ON personnel (username)');
        $this->addSql('CREATE TABLE service (id UUID NOT NULL, nom_ser VARCHAR(255) NOT NULL, nomen_ser VARCHAR(255) NOT NULL, direction_id_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E19D9AD2BDBDA0BA ON service (nom_ser)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E19D9AD28C61C060 ON service (nomen_ser)');
        $this->addSql('CREATE INDEX IDX_E19D9AD27EB353A ON service (direction_id_id)');
        $this->addSql('CREATE TABLE type_document (id UUID NOT NULL, nom_type_doc VARCHAR(255) NOT NULL, dossier_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1596AD8A111CDE0C ON type_document (nom_type_doc)');
        $this->addSql('CREATE INDEX IDX_1596AD8AB6C48410 ON type_document (dossier_id_id)');
        $this->addSql('ALTER TABLE agence_personnel ADD CONSTRAINT FK_28239427D1F6E7C3 FOREIGN KEY (agence_id_id) REFERENCES agence (id)');
        $this->addSql('ALTER TABLE agence_personnel ADD CONSTRAINT FK_28239427588DF5E9 FOREIGN KEY (personnel_id_id) REFERENCES personnel (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conjoint ADD CONSTRAINT FK_2F91A10D1C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE direction_personnel ADD CONSTRAINT FK_CD9C37A9588DF5E9 FOREIGN KEY (personnel_id_id) REFERENCES personnel (id)');
        $this->addSql('ALTER TABLE direction_personnel ADD CONSTRAINT FK_CD9C37A9D63673B0 FOREIGN KEY (service_id_id) REFERENCES service (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76588DF5E9 FOREIGN KEY (personnel_id_id) REFERENCES personnel (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A764026C1B1 FOREIGN KEY (type_document_id_id) REFERENCES type_document (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE enfant ADD CONSTRAINT FK_34B70CA21C109075 FOREIGN KEY (personnel_id) REFERENCES personnel (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fonction ADD CONSTRAINT FK_900D5BD8A3C7387 FOREIGN KEY (categorie_id_id) REFERENCES categorie (id)');
        $this->addSql('ALTER TABLE personnel ADD CONSTRAINT FK_A6BCF3DE1DECB9C6 FOREIGN KEY (fonction_id_id) REFERENCES fonction (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD27EB353A FOREIGN KEY (direction_id_id) REFERENCES direction (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE type_document ADD CONSTRAINT FK_1596AD8AB6C48410 FOREIGN KEY (dossier_id_id) REFERENCES dossier (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE agence_personnel DROP CONSTRAINT FK_28239427D1F6E7C3');
        $this->addSql('ALTER TABLE agence_personnel DROP CONSTRAINT FK_28239427588DF5E9');
        $this->addSql('ALTER TABLE conjoint DROP CONSTRAINT FK_2F91A10D1C109075');
        $this->addSql('ALTER TABLE direction_personnel DROP CONSTRAINT FK_CD9C37A9588DF5E9');
        $this->addSql('ALTER TABLE direction_personnel DROP CONSTRAINT FK_CD9C37A9D63673B0');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76588DF5E9');
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A764026C1B1');
        $this->addSql('ALTER TABLE enfant DROP CONSTRAINT FK_34B70CA21C109075');
        $this->addSql('ALTER TABLE fonction DROP CONSTRAINT FK_900D5BD8A3C7387');
        $this->addSql('ALTER TABLE personnel DROP CONSTRAINT FK_A6BCF3DE1DECB9C6');
        $this->addSql('ALTER TABLE service DROP CONSTRAINT FK_E19D9AD27EB353A');
        $this->addSql('ALTER TABLE type_document DROP CONSTRAINT FK_1596AD8AB6C48410');
        $this->addSql('DROP TABLE agence');
        $this->addSql('DROP TABLE agence_personnel');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE conjoint');
        $this->addSql('DROP TABLE direction');
        $this->addSql('DROP TABLE direction_personnel');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE dossier');
        $this->addSql('DROP TABLE enfant');
        $this->addSql('DROP TABLE fonction');
        $this->addSql('DROP TABLE personnel');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE type_document');
    }
}
