# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    default_locale: fr
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        cookie_secure: auto
        cookie_samesite: lax
        gc_maxlifetime: 7200
        handler_id: 'redis://:%env(REDIS_PASSWORD)%@redis:6379'
    csrf_protection:
    serializer:
        enabled: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
